### ISSUE TITLE
Flutter bloc 4.x.x to 6.x.x migration?

### ISSUE THREAD

**Issue by chainchelliah** [TheAlphamerc/flutter_spacexopedia#3]
Hi, 
I'm a newbiee to flutter world. I was looking around the samples and yours very much impressive.
So, do you have any plan to migrate or use flutter_bloc 6.x.x in any other projects? Or else any particular reason you stick to 4.x.x. Your thought  would be very helpful. 
Thanks.

**Comment by TheAlphamerc** [comment]
Hi @chainchelliah, When I have started working on this project I didn't aware of the new version of BLoc so I have worked with  Bloc version 4.x.x. Currently, I have no plan to migrate to a newer version as this project is in a stable version.
In my future projects, I will prefer new version of Bloc to work with.
Thanks for taking interest in the project.

**Comment by TheAlphamerc** [comment]
Currently I am working on [GitConnect](https://github.com/TheAlphamerc/flutter-GitConnect) application.
I have used bloc v4.0.0 in it but now I have decided to migrate it to bloc v6.0.0.
To migrate this application to newer version of bloc it will take 2-3 days.

**Comment by chainchelliah** [comment]
> Currently I am working on [GitConnect](https://github.com/TheAlphamerc/flutter-GitConnect) application.
> I have used bloc v4.0.0 in it but now I have decided to migrate it to bloc v6.0.0.
> To migrate this application to newer version of bloc it will take 2-3 days.

Thanks for your quick response.  
Great, I will surely have a look and am curious how it is going to affect the existing one.

**Comment by TheAlphamerc** [comment]
@chainchelliah In [GitConnect](https://github.com/TheAlphamerc/flutter-GitConnect) project Bloc is migrated to v6.0.0.
You can check it now.

**Comment by chainchelliah** [comment]
> @chainchelliah In [GitConnect](https://github.com/TheAlphamerc/flutter-GitConnect) project Bloc is migrated to v6.0.0.
> You can check it now.

Unbelievable Stuff!!! You really made my day!!!
Thanks a lot...
